### ISSUE TITLE
fails to start

### ISSUE THREAD

**Issue by johntom** [smartiniOnGitHub/fastify-example#11]
Hi,
Trying to run example windows 10 node 16.15.0 and tested with 17.15.0
```
 nvm use 16.15.0
Now using node v16.15.0 (64-bit)
PS D:\fastify-gp\fastify-example> npm start

> fastify-example@4.0.0 start
> node ./src/server

Server starting for fastify-example-v4.0.0 ...
Webapp features enabled: '{"platformInfo":true,"checkRuntimeEnv":true,"favicon":true,"webhook":true,"healthcheck":true,"cloudevents":true,"cloudeventsStrictMode":true,"cloudeventsLogConsole":true,"cloudeventsLogFile":false,"nats":true}'
{"level":30,"time":1661007826400,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Node.js v16.15.0, running on OS: win32"}
{"level":30,"time":1661007826401,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Webapp fastify-example-v4.0.0, running on Fastify-v4.5.2"}
{"level":30,"time":1661007826401,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Webapp features enabled: '{\"platformInfo\":true,\"checkRuntimeEnv\":true,\"favicon\":true,\"webhook\":true,\"healthcheck\":true,\"cloudevents\":true,\"cloudeventsStrictMode\":true,\"cloudeventsLogConsole\":true,\"cloudeventsLogFile\":false,\"nats\":true}'"}
{"level":30,"time":1661007826407,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Server Startup script successfully executed"}
Connected to the queue server at: 'demo.nats.io:4222'
{"level":30,"time":1661007831704,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Webapp features loaded"}
Printing Routes (env 'development'), only for non production environments
└── / (-)
    ├── favicon.ico (GET, HEAD)
    ├── health (GET, HEAD)
    └── static/* (HEAD, GET)

Subscribe to messages from the queue 'fastify-example-4.0.0'
Publish message in the queue 'fastify-example-4.0.0'
Server listening on 'http://127.0.0.1:8000' ...
{"level":30,"time":1661007831716,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Printing Routes (env 
'development'), only for non production environments\nΓööΓöÇΓöÇ / (-)\n    Γö£ΓöÇΓöÇ favicon.ico (GET, HEAD)\n    Γö£ΓöÇΓöÇ health (GET, HEAD)\n    ΓööΓöÇΓöÇ static/* (HEAD, GET)\n"}
{"level":30,"time":1661007831738,"pid":28600,"hostname":"DESKTOP-TF4IHHA","msg":"Server listening at http://127.0.0.1:8000"}

D:\fastify-gp\fastify-example\node_modules\avvio\boot.js:244
    throw new AVV_ERR_ROOT_PLG_BOOTED()
          ^
AvvioError [Error]: Root plugin has already booted
    at Boot._addPlugin (D:\fastify-gp\fastify-example\node_modules\avvio\boot.js:244:11)
    at Boot.use (D:\fastify-gp\fastify-example\node_modules\avvio\boot.js:216:25)
    at Object.server.<computed> [as register] (D:\fastify-gp\fastify-example\node_modules\avvio\boot.js:40:14)
    at app (D:\fastify-gp\fastify-example\src\app.js:94:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'AVV_ERR_PLUGIN_NOT_VALID'
}
```

**Comment by smartiniOnGitHub** [comment]
Hi, thanks for all the info, it's a weird thing, sorry; I'll look at it ASAP and tell you.

**Comment by smartiniOnGitHub** [comment]
Hi, just re-enabled all my plugins (now compatible with Fastify 4.x) and related features in code.
Tested with Node.js v16.17.0 on Linux and all works (I'm using latest Fastify 4.5.2 now, released few days ago).
I'm sorry but can't test anymore in Windows (I have to setup CI here).
In case something still doesn't work, try to disable some feature like NATS (in corporate networks sometimes NATS public/demo server is not reachable) via related env var (and written in the README).
Keep me updated. Bye

**Comment by johntom** [comment]
Thanks, I will test and get back to you,

**Comment by johntom** [comment]
That fixed everything without any mods!
Thanks again
